# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='url',
            new_name='requested_view',
        ),
    ]
